# NUMPY
Numpy is pythons packahae for maths more than +,-*/
This includes functions like cosine, exponent, sqrt..
We can also use numpy to generate samples from many type of random variables
numpy also have powerful data types to define vectors, matrics, and tensors
With these packages Numpy allows to do linear algebra, matric multiplicationand matric-vector solution

In [1]:
import numpy as np

In [4]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [6]:
# We can create numpy arrays by converting list
#this is a vector
vec= np.array([1,2,3])
print(vec)
#We can create matrices by converting lists of lists
mat =np.array([[1,2,3],[4,5,6],[7,8,9]])
print('')
print(mat)
print('')
print(mat.T) # Transpose of the matrix

[1 2 3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
#There are lot of other ways to create a nump array
vec2 = np.arange(0,15)  #This is arange not range, arange is array of range
print(vec2)
print('')
vec3=np.arange(3,21,6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [11]:
vec4 = np.linspace(0,5,10)  #linspace includes both first and last, while range/arange recall last value is not included
print(vec4)
print('')
print(vec4.reshape(5,2))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [12]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones([3,5])
print(mat3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Accessing entries in a nump array and matrices

In [16]:
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 2.35129897 -1.30361467  1.12228714  0.93831605  2.79021843 -0.34890143
  0.04177211  2.08542831 -0.12684912 -0.24977601  0.33388757  0.25377981
 -0.12702324  0.01244026 -1.90354144  2.53327156 -0.69243383 -0.74325956
  0.44498276]
0.04177211279980581


In [18]:
# We can access mulitple entries at once
print(rand_vec[4:9])  #no to right of colon is excluded, left is included

[ 2.79021843 -0.34890143  0.04177211  2.08542831 -0.12684912]


In [20]:
#We can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print('')
print(rand_vec[np.arange(0,15,3)])  #We passed the incdex which we created using arange and we are searching the values for this index in the rand_vec

[ 0  3  6  9 12]

[ 2.35129897  0.93831605  0.04177211 -0.24977601 -0.12702324]


In [49]:
rand_mat = np.arange(1,21,1)
rand_mat1 = rand_mat.reshape(5,4)
print(rand_mat)
print('')
print(rand_mat1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [32]:
print(rand_mat1[1][1])
print(rand_mat1[1,1])   #Please note rows and columns are seperated by a comma

6
6


In [35]:
print(rand_mat1[0:2, 0:2])  # rows 0,1 and not 2  | colum 0,1 and not 2

[[1 2]
 [5 6]]


In [43]:
#Lest change some values in an array!
print(rand_vec)
print ('')
rand_vec[1:2]=6000
print(rand_vec)
rand_vec[1:3]=6000
print(rand_vec)
print ('')

[ 2.35129897e+00  6.00000000e+03  1.12228714e+00  9.38316049e-01
  2.79021843e+00 -3.48901429e-01  4.17721128e-02  2.08542831e+00
 -1.26849122e-01 -2.49776015e-01  3.33887571e-01  2.53779811e-01
 -1.27023235e-01  1.24402559e-02 -1.90354144e+00  2.53327156e+00
 -6.92433827e-01 -7.43259557e-01  4.44982757e-01]

[ 2.35129897e+00  6.00000000e+03  1.12228714e+00  9.38316049e-01
  2.79021843e+00 -3.48901429e-01  4.17721128e-02  2.08542831e+00
 -1.26849122e-01 -2.49776015e-01  3.33887571e-01  2.53779811e-01
 -1.27023235e-01  1.24402559e-02 -1.90354144e+00  2.53327156e+00
 -6.92433827e-01 -7.43259557e-01  4.44982757e-01]
[ 2.35129897e+00  6.00000000e+03  6.00000000e+03  9.38316049e-01
  2.79021843e+00 -3.48901429e-01  4.17721128e-02  2.08542831e+00
 -1.26849122e-01 -2.49776015e-01  3.33887571e-01  2.53779811e-01
 -1.27023235e-01  1.24402559e-02 -1.90354144e+00  2.53327156e+00
 -6.92433827e-01 -7.43259557e-01  4.44982757e-01]



In [53]:
#Lest change some values in a matrics!
print(rand_mat1)
print ('')
rand_mat1[1:2,3]=888
print(rand_mat1)
print ('')

[[   1    2    3    4]
 [6000 6000 6000 6000]
 [   9   10   11   12]
 [  13   14   15   16]
 [  17   18   19   20]]

[[   1    2    3    4]
 [6000 6000 6000  888]
 [   9   10   11   12]
 [  13   14   15   16]
 [  17   18   19   20]]



In [58]:
#We can also access entries with logicls
rand_vec = np.random.randn(15)
print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[ 0.50439135 -0.22437448  0.21275721 -0.10432259 -0.19609928  0.45053306
 -0.10984372 -0.73316482 -0.40139334 -0.34687615  0.95079103 -1.66480099
  0.13085551 -0.71638012 -0.84031761]
[ True False  True False False  True False False False False  True False
  True False False]
[0.50439135 0.21275721 0.45053306 0.95079103 0.13085551]


In [60]:
print(rand_mat1)
print(rand_mat1>0)
print(rand_mat1[rand_mat1>0])

[[   1    2    3    4]
 [6000 6000 6000  888]
 [   9   10   11   12]
 [  13   14   15   16]
 [  17   18   19   20]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[   1    2    3    4 6000 6000 6000  888    9   10   11   12   13   14
   15   16   17   18   19   20]


In [61]:
print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = 5000
print(rand_vec)

[ 0.50439135 -0.22437448  0.21275721 -0.10432259 -0.19609928  0.45053306
 -0.10984372 -0.73316482 -0.40139334 -0.34687615  0.95079103 -1.66480099
  0.13085551 -0.71638012 -0.84031761]

[ 5.00000000e+03 -2.24374476e-01  2.12757214e-01 -1.04322588e-01
 -1.96099281e-01  4.50533063e-01 -1.09843715e-01 -7.33164825e-01
 -4.01393335e-01 -3.46876147e-01  5.00000000e+03 -1.66480099e+00
  1.30855505e-01 -7.16380116e-01 -8.40317608e-01]


In [62]:
#Saving an array on the disk for use later
np.save('saved_file_name',rand_mat1)

In [63]:
#Saving more than one numpy array
np.savez('Ziffed_file_name',rand_mat = rand_mat, rand_mat1=rand_mat1)

In [64]:
#now lets load it
loaded_vec = np.load('saved_file_name.npy')
loaded_Zip = np.load('Ziffed_file_name.npz')
print(loaded_vec)
print('')
print(loaded_Zip)

[[   1    2    3    4]
 [6000 6000 6000  888]
 [   9   10   11   12]
 [  13   14   15   16]
 [  17   18   19   20]]



In [65]:
print(loaded_Zip['rand_mat'])
print('')
print(loaded_Zip['rand_mat1'])

[   1    2    3    4 6000 6000 6000  888    9   10   11   12   13   14
   15   16   17   18   19   20]

[[   1    2    3    4]
 [6000 6000 6000  888]
 [   9   10   11   12]
 [  13   14   15   16]
 [  17   18   19   20]]


In [68]:
# We can also save/load  as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter =',')

In [69]:
loade_txt = np.loadtxt('text_file_name.txt',delimiter =',')
print(loade_txt)

[1.00e+00 2.00e+00 3.00e+00 4.00e+00 6.00e+03 6.00e+03 6.00e+03 8.88e+02
 9.00e+00 1.00e+01 1.10e+01 1.20e+01 1.30e+01 1.40e+01 1.50e+01 1.60e+01
 1.70e+01 1.80e+01 1.90e+01 2.00e+01]


# PANDAS

In [70]:
#Dataframes are more flexible than nump arrays 
#(array all columns of one datatype, whereas dataframe can have varius columns of varius datatypes)
#Pandas has SQL like merge,join and sorting

In [72]:
import pandas as pd
import numpy as np

## Pandas Series & Dataframes

In [74]:
# First let look st Series : think of this as a single column in a spreadsheet
#each entry ini the series corresponds to an individual row in the spreadsheet
#We can create a series by converting  list, or numpy array

mylist = [5.4,6.1,1.7,99.8]
myarray= np.array(mylist)

In [75]:
myseries1 = pd.Series(data=mylist)
print(myseries1)
myseries2 = pd.Series(data=myarray)
print(myseries1)


0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64
0     5.4
1     6.1
2     1.7
3    99.8
dtype: float64


In [76]:
# We can access the values in a series simillar to that of numpy arrays
print(myseries1[2])

1.7


In [ ]:
#We can add labels to the entries of a Series

In [77]:
mylabels = ['first','second','third','fourth']
myseries3=pd.Series(data=mylist,index=mylabels)
print(myseries3)

first      5.4
second     6.1
third      1.7
fourth    99.8
dtype: float64


In [ ]:
# We need not be explicit about the entries of ps.Series

In [78]:
myseries4 = pd.Series (mylist,mylabels)
print(myseries4)

first      5.4
second     6.1
third      1.7
fourth    99.8
dtype: float64


In [79]:
print(myseries4['second'])

6.1


In [80]:
#We can do math on series
myseries5 = pd.Series([5.5,1.1,8.8,1.6],['first','third','fourth','fifth'])
print(myseries5)
print('')
print(myseries5+myseries4)

first     5.5
third     1.1
fourth    8.8
fifth     1.6
dtype: float64

fifth       NaN
first      10.9
fourth    108.6
second      NaN
third       2.8
dtype: float64


In [85]:
#We can combine series to create a dataframe using concat function
df1 = pd.concat([myseries4,myseries5],axis=1,sort=False)  #axis =1 for columns
df1

0    1
first    5.4  5.5
second   6.1  NaN
third    1.7  1.1
fourth  99.8  8.8
fifth    NaN  1.6

In [86]:
#We can create a dataframe
df2= pd.DataFrame(np.random.randn(5,5))
df2

0         1         2         3         4
0  1.778185  1.860801  0.623772 -0.478987 -0.748002
1 -0.001599  0.001036 -0.183254 -0.838611  1.011648
2  1.000801 -0.966229  0.144563  0.458815  0.200022
3 -0.050695 -0.421848  0.407281 -0.758869  0.071483
4 -0.496486  0.711243  0.816412 -0.198576 -1.150655

In [90]:
#We can give labels to rows and columns
df3 = pd.DataFrame(np.random.randn(5,5),index= ['first row','second row', 'third row', 'fourth row','fifth row'],
columns=['first col','second col','third col','fourth col','fifth col'])
df3

first col  second col  third col  fourth col  fifth col
first row   -0.671262   -0.098627  -0.334107   -0.179872  -0.603082
second row   1.073925    0.914730  -0.808270   -0.427714   0.407046
third row    0.136185    1.225036   0.352677    1.028644   0.175849
fourth row   0.037277    0.522727   0.770994   -0.518204  -1.312977
fifth row   -0.165082    1.905732   0.074423    0.090313  -0.276045

In [91]:
# We can access individual serie in df
print(df3['second col'])
print('')
df3[['third col','fourth col']]

first row    -0.098627
second row    0.914730
third row     1.225036
fourth row    0.522727
fifth row     1.905732
Name: second col, dtype: float64



third col  fourth col
first row   -0.334107   -0.179872
second row  -0.808270   -0.427714
third row    0.352677    1.028644
fourth row   0.770994   -0.518204
fifth row    0.074423    0.090313

In [93]:
#We can access rows of a df
df3.loc['fourth row'] #loc is for location

first col     0.037277
second col    0.522727
third col     0.770994
fourth col   -0.518204
fifth col    -1.312977
Name: fourth row, dtype: float64

In [97]:
df3.iloc[2]

first col     0.136185
second col    1.225036
third col     0.352677
fourth col    1.028644
fifth col     0.175849
Name: third row, dtype: float64

In [98]:
a = 'abc'
b = '200'
print(a+b)

abc200
